services:
  drawlingo-api:
    build:
      context: ./drawlingo-api
      dockerfile: Dockerfile.development
    restart: always
    volumes:
      - ./drawlingo-api:/home/app
      - /home/app/node_modules
    ports:
      - "5050:5050"
    env_file:
      - ./drawlingo-api/.env
    depends_on:
      - redis
    networks:
      - drawlingo-net

  drawlingo-app:
    build:
      context: ./drawlingo-app
      dockerfile: Dockerfile.development
    restart: always
    volumes:
      - ./drawlingo-app:/home/app
      - /home/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./drawlingo-app/.env
    depends_on:
      - redis
      - drawlingo-api
    networks:
      - drawlingo-net
    stdin_open: true
    tty: true

  redis:
    image: redis:7.0
    restart: always
    volumes:
      - ./volumes/redis:/data
    networks:
      - drawlingo-net
    ports:
      - "6379:6379"

networks:
  drawlingo-net:
